using System;
using System.Collections.Generic;
using System.Text;

namespace Contacts.Domain.Helper
{
    public static class HelperCountry
    {
        public static Array GetAllCountries()
        {
            return new[]{
                                    new{ Value="55",Text ="Brazil (+55)"},
                                    new{ Value="1",Text ="USA (+1)"},
                                    new{ Value="44" ,Text ="UK (+44)"},
                                    new{ Value="213",Text ="Algeria (+213)"},
                                    new{ Value="376",Text ="Andorra (+376)"},
                                    new{ Value="244",Text ="Angola (+244)"},
                                    new{ Value="1264",Text ="Anguilla (+1264)"},
                                    new{ Value="1268",Text ="Antigua &amp; Barbuda (+1268)"},
                                    new{ Value="54",Text ="Argentina (+54)"},
                                    new{ Value="374",Text ="Armenia (+374)"},
                                    new{ Value="297",Text ="Aruba (+297)"},
                                    new{ Value="61",Text ="Australia (+61)"},
                                    new{ Value="43",Text ="Austria (+43)"},
                                    new{ Value="994",Text ="Azerbaijan (+994)"},
                                    new{ Value="1242",Text ="Bahamas (+1242)"},
                                    new{ Value="973",Text ="Bahrain (+973)"},
                                    new{ Value="880",Text ="Bangladesh (+880)"},
                                    new{ Value="1246",Text ="Barbados (+1246)"},
                                    new{ Value="375",Text ="Belarus (+375)"},
                                    new{ Value="32",Text ="Belgium (+32)"},
                                    new{ Value="501",Text ="Belize (+501)"},
                                    new{ Value="229",Text ="Benin (+229)"},
                                    new{ Value="1441",Text ="Bermuda (+1441)"},
                                    new{ Value="975",Text ="Bhutan (+975)"},
                                    new{ Value="591",Text ="Bolivia (+591)"},
                                    new{ Value="387",Text ="Bosnia Herzegovina (+387)"},
                                    new{ Value="267",Text ="Botswana (+267)"},
                                    new{ Value="55",Text ="Brazil (+55)"},
                                    new{ Value="673",Text ="Brunei (+673)"},
                                    new{ Value="359",Text ="Bulgaria (+359)"},
                                    new{ Value="226",Text ="Burkina Faso (+226)"},
                                    new{ Value="257",Text ="Burundi (+257)"},
                                    new{ Value="855",Text ="Cambodia (+855)"},
                                    new{ Value="237",Text ="Cameroon (+237)"},
                                    new{ Value="1",Text ="Canada (+1)"},
                                    new{ Value="238",Text ="Cape Verde Islands (+238)"},
                                    new{ Value="1345",Text ="Cayman Islands (+1345)"},
                                    new{ Value="236",Text ="Central African Republic (+236)"},
                                    new{ Value="56",Text ="Chile (+56)"},
                                    new{ Value="86",Text ="China (+86)"},
                                    new{ Value="57",Text ="Colombia (+57)"},
                                    new{ Value="269",Text ="Comoros (+269)"},
                                    new{ Value="242",Text ="Congo (+242)"},
                                    new{ Value="682",Text ="Cook Islands (+682)"},
                                    new{ Value="506",Text ="Costa Rica (+506)"},
                                    new{ Value="385",Text ="Croatia (+385)"},
                                    new{ Value="53",Text ="Cuba (+53)"},
                                    new{ Value="90392",Text ="Cyprus North (+90392)"},
                                    new{ Value="357",Text ="Cyprus South (+357)"},
                                    new{ Value="42",Text ="Czech Republic (+42)"},
                                    new{ Value="45",Text ="Denmark (+45)"},
                                    new{ Value="253",Text ="Djibouti (+253)"},
                                    new{ Value="1809",Text ="Dominica (+1809)"},
                                    new{ Value="1809",Text ="Dominican Republic (+1809)"},
                                    new{ Value="593",Text ="Ecuador (+593)"},
                                    new{ Value="20",Text ="Egypt (+20)"},
                                    new{ Value="503",Text ="El Salvador (+503)"},
                                    new{ Value="240",Text ="Equatorial Guinea (+240)"},
                                    new{ Value="291",Text ="Eritrea (+291)"},
                                    new{ Value="372",Text ="Estonia (+372)"},
                                    new{ Value="251",Text ="Ethiopia (+251)"},
                                    new{ Value="500",Text ="Falkland Islands (+500)"},
                                    new{ Value="298",Text ="Faroe Islands (+298)"},
                                    new{ Value="679",Text ="Fiji (+679)"},
                                    new{ Value="358",Text ="Finland (+358)"},
                                    new{ Value="33",Text ="France (+33)"},
                                    new{ Value="594",Text ="French Guiana (+594)"},
                                    new{ Value="689",Text ="French Polynesia (+689)"},
                                    new{ Value="241",Text ="Gabon (+241)"},
                                    new{ Value="220",Text ="Gambia (+220)"},
                                    new{ Value="7880",Text ="Georgia (+7880)"},
                                    new{ Value="49",Text ="Germany (+49)"},
                                    new{ Value="233",Text ="Ghana (+233)"},
                                    new{ Value="350",Text ="Gibraltar (+350)"},
                                    new{ Value="30",Text ="Greece (+30)"},
                                    new{ Value="299",Text ="Greenland (+299)"},
                                    new{ Value="1473",Text ="Grenada (+1473)"},
                                    new{ Value="590",Text ="Guadeloupe (+590)"},
                                    new{ Value="671",Text ="Guam (+671)"},
                                    new{ Value="502",Text ="Guatemala (+502)"},
                                    new{ Value="224",Text ="Guinea (+224)"},
                                    new{ Value="245",Text ="Guinea - Bissau (+245)"},
                                    new{ Value="592",Text ="Guyana (+592)"},
                                    new{ Value="509",Text ="Haiti (+509)"},
                                    new{ Value="504",Text ="Honduras (+504)"},
                                    new{ Value="852",Text ="Hong Kong (+852)"},
                                    new{ Value="36",Text ="Hungary (+36)"},
                                    new{ Value="354",Text ="Iceland (+354)"},
                                    new{ Value="91",Text ="India (+91)"},
                                    new{ Value="62",Text ="Indonesia (+62)"},
                                    new{ Value="98",Text ="Iran (+98)"},
                                    new{ Value="964",Text ="Iraq (+964)"},
                                    new{ Value="353",Text ="Ireland (+353)"},
                                    new{ Value="972",Text ="Israel (+972)"},
                                    new{ Value="39",Text ="Italy (+39)"},
                                    new{ Value="1876",Text ="Jamaica (+1876)"},
                                    new{ Value="81",Text ="Japan (+81)"},
                                    new{ Value="962",Text ="Jordan (+962)"},
                                    new{ Value="7",Text ="Kazakhstan (+7)"},
                                    new{ Value="254",Text ="Kenya (+254)"},
                                    new{ Value="686",Text ="Kiribati (+686)"},
                                    new{ Value="850",Text ="Korea North (+850)"},
                                    new{ Value="82",Text ="Korea South (+82)"},
                                    new{ Value="965",Text ="Kuwait (+965)"},
                                    new{ Value="996",Text ="Kyrgyzstan (+996)"},
                                    new{ Value="856",Text ="Laos (+856)"},
                                    new{ Value="371",Text ="Latvia (+371)"},
                                    new{ Value="961",Text ="Lebanon (+961)"},
                                    new{ Value="266",Text ="Lesotho (+266)"},
                                    new{ Value="231",Text ="Liberia (+231)"},
                                    new{ Value="218",Text ="Libya (+218)"},
                                    new{ Value="417",Text ="Liechtenstein (+417)"},
                                    new{ Value="370",Text ="Lithuania (+370)"},
                                    new{ Value="352",Text ="Luxembourg (+352)"},
                                    new{ Value="853",Text ="Macao (+853)"},
                                    new{ Value="389",Text ="Macedonia (+389)"},
                                    new{ Value="261",Text ="Madagascar (+261)"},
                                    new{ Value="265",Text ="Malawi (+265)"},
                                    new{ Value="60",Text ="Malaysia (+60)"},
                                    new{ Value="960",Text ="Maldives (+960)"},
                                    new{ Value="223",Text ="Mali (+223)"},
                                    new{ Value="356",Text ="Malta (+356)"},
                                    new{ Value="692",Text ="Marshall Islands (+692)"},
                                    new{ Value="596",Text ="Martinique (+596)"},
                                    new{ Value="222",Text ="Mauritania (+222)"},
                                    new{ Value="269",Text ="Mayotte (+269)"},
                                    new{ Value="52",Text ="Mexico (+52)"},
                                    new{ Value="691",Text ="Micronesia (+691)"},
                                    new{ Value="373",Text ="Moldova (+373)"},
                                    new{ Value="377",Text ="Monaco (+377)"},
                                    new{ Value="976",Text ="Mongolia (+976)"},
                                    new{ Value="1664",Text ="Montserrat (+1664)"},
                                    new{ Value="212",Text ="Morocco (+212)"},
                                    new{ Value="258",Text ="Mozambique (+258)"},
                                    new{ Value="95",Text ="Myanmar (+95)"},
                                    new{ Value="264",Text ="Namibia (+264)"},
                                    new{ Value="674",Text ="Nauru (+674)"},
                                    new{ Value="977",Text ="Nepal (+977)"},
                                    new{ Value="31",Text ="Netherlands (+31)"},
                                    new{ Value="687",Text ="New Caledonia (+687)"},
                                    new{ Value="64",Text ="New Zealand (+64)"},
                                    new{ Value="505",Text ="Nicaragua (+505)"},
                                    new{ Value="227",Text ="Niger (+227)"},
                                    new{ Value="234",Text ="Nigeria (+234)"},
                                    new{ Value="683",Text ="Niue (+683)"},
                                    new{ Value="672",Text ="Norfolk Islands (+672)"},
                                    new{ Value="670",Text ="Northern Marianas (+670)"},
                                    new{ Value="47",Text ="Norway (+47)"},
                                    new{ Value="968",Text ="Oman (+968)"},
                                    new{ Value="680",Text ="Palau (+680)"},
                                    new{ Value="507",Text ="Panama (+507)"},
                                    new{ Value="675",Text ="Papua New Guinea (+675)"},
                                    new{ Value="595",Text ="Paraguay (+595)"},
                                    new{ Value="51",Text ="Peru (+51)"},
                                    new{ Value="63",Text ="Philippines (+63)"},
                                    new{ Value="48",Text ="Poland (+48)"},
                                    new{ Value="351",Text ="Portugal (+351)"},
                                    new{ Value="1787",Text ="Puerto Rico (+1787)"},
                                    new{ Value="974",Text ="Qatar (+974)"},
                                    new{ Value="262",Text ="Reunion (+262)"},
                                    new{ Value="40",Text ="Romania (+40)"},
                                    new{ Value="7",Text ="Russia (+7)"},
                                    new{ Value="250",Text ="Rwanda (+250)"},
                                    new{ Value="378",Text ="San Marino (+378)"},
                                    new{ Value="239",Text ="Sao Tome &amp; Principe (+239)"},
                                    new{ Value="966",Text ="Saudi Arabia (+966)"},
                                    new{ Value="221",Text ="Senegal (+221)"},
                                    new{ Value="381",Text ="Serbia (+381)"},
                                    new{ Value="248",Text ="Seychelles (+248)"},
                                    new{ Value="232",Text ="Sierra Leone (+232)"},
                                    new{ Value="65",Text ="Singapore (+65)"},
                                    new{ Value="421",Text ="Slovak Republic (+421)"},
                                    new{ Value="386",Text ="Slovenia (+386)"},
                                    new{ Value="677",Text ="Solomon Islands (+677)"},
                                    new{ Value="252",Text ="Somalia (+252)"},
                                    new{ Value="27",Text ="South Africa (+27)"},
                                    new{ Value="34",Text ="Spain (+34)"},
                                    new{ Value="94",Text ="Sri Lanka (+94)"},
                                    new{ Value="290",Text ="St. Helena (+290)"},
                                    new{ Value="1869",Text ="St. Kitts (+1869)"},
                                    new{ Value="1758",Text ="St. Lucia (+1758)"},
                                    new{ Value="249",Text ="Sudan (+249)"},
                                    new{ Value="597",Text ="Suriname (+597)"},
                                    new{ Value="268",Text ="Swaziland (+268)"},
                                    new{ Value="46",Text ="Sweden (+46)"},
                                    new{ Value="41",Text ="Switzerland (+41)"},
                                    new{ Value="963",Text ="Syria (+963)"},
                                    new{ Value="886",Text ="Taiwan (+886)"},
                                    new{ Value="7",Text ="Tajikstan (+7)"},
                                    new{ Value="66",Text ="Thailand (+66)"},
                                    new{ Value="228",Text ="Togo (+228)"},
                                    new{ Value="676",Text ="Tonga (+676)"},
                                    new{ Value="1868",Text ="Trinidad &amp; Tobago (+1868)"},
                                    new{ Value="216",Text ="Tunisia (+216)"},
                                    new{ Value="90",Text ="Turkey (+90)"},
                                    new{ Value="7",Text ="Turkmenistan (+7)"},
                                    new{ Value="993",Text ="Turkmenistan (+993)"},
                                    new{ Value="1649",Text ="Turks &amp; Caicos Islands (+1649)"},
                                    new{ Value="688",Text ="Tuvalu (+688)"},
                                    new{ Value="256",Text ="Uganda (+256)"},
                                    new{ Value="44",Text ="UK (+44)"},
                                    new{ Value="380",Text ="Ukraine (+380)"},
                                    new{ Value="971",Text ="United Arab Emirates (+971)"},
                                    new{ Value="598",Text ="Uruguay (+598)"},
                                    new{ Value="1",Text ="USA (+1)"},
                                    new{ Value="7",Text ="Uzbekistan (+7)"},
                                    new{ Value="678",Text ="Vanuatu (+678)"},
                                    new{ Value="379",Text ="Vatican City (+379)"},
                                    new{ Value="58",Text ="Venezuela (+58)"},
                                    new{ Value="84",Text ="Vietnam (+84)"},
                                    new{ Value="84",Text ="Virgin Islands - British (+1284)"},
                                    new{ Value="84",Text ="Virgin Islands - US (+1340)"},
                                    new{ Value="681",Text ="Wallis &amp; Futuna (+681)"},
                                    new{ Value="969",Text ="Yemen (North)(+969)"},
                                    new{ Value="967",Text ="Yemen (South)(+967)"},
                                    new{ Value="260",Text ="Zambia (+260)"},
                                    new{ Value="263",Text ="Zimbabwe (+263)"},
                                };
        }
    }
}
